# Generated by Django 3.2.19 on 2024-02-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.CharField(default='Food', max_length=20),
        ),
    ]
