# Generated by Django 3.2.19 on 2024-02-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_seller', '0003_food_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_category',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
