# Generated by Django 3.2.19 on 2024-02-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_seller', '0004_auto_20240228_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
