# Generated by Django 3.2.19 on 2024-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_seller', '0005_alter_food_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.CharField(choices=[('F', 'Food'), ('D', 'Drink')], default='F', max_length=2),
        ),
    ]
