# Generated by Django 3.2.19 on 2024-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_seller', '0006_food_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.CharField(blank=True, default='img/img_coming_soon.png', max_length=255, null=True),
        ),
    ]
